---
title: "Rmd Practice"
output: 
  html_document: 
    keep_md: yes
---

My name is Emily. 
```{r}
library(ggvis)
library(nycflights13)
library(dplyr)
library(EDAWR)
library(tidyr)
```


Rmd can make equations like Latex: $\frac{1}{n} \sum{i=i}^{n} x_{i}$

It can also include links like this: [linked phrase](http://rmarkdown.rstudio.com/authoring_basics.html)

# **Plot 1**
- made up data points
```{r echo = FALSE}
xval <- c(1,2,3,4,5)
yval <- c(8,3,2,5,8)
df <- data.frame(xval, yval)

df %>% ggvis(x = ~xval, y = ~yval) %>% layer_points() #creates a plot!

```

# **Plot 2**
- flights example from R tutorial
```{r echo = FALSE}
flights %>% left_join(airlines, by = "carrier") %>% 
  droplevels() %>% 
  filter(!is.na(arr_delay)) %>%  
  ggvis(x = ~name, y = ~arr_delay, fill = ~name) %>% layer_boxplots()

```

# **Plot 3**
- china example from R tutorial
```{r echo = FALSE, eval = TRUE}
tb2 <- tb %>% mutate(tcases = child + adult + elderly) %>% filter(!is.na(tcases)) %>% 
  group_by(country, year) %>% summarise(cases = sum(tcases)) %>% ungroup() 

tb3 <- population %>% gather("year", "population", -1, convert = TRUE) %>% 
  right_join(tb2, by = c("country", "year")) %>% mutate(rate = cases/population * 10000)

china <- tb3 %>%  filter(country == "China")

china %>% ggvis(~population, ~cases, fill := "red") %>% layer_points()

```

# **Plot 4**
- same as first plot, but using plot instead of ggvis
```{r}
xval <- c(1,2,3,4,5)
yval <- c(8,3,2,5,8)

plot(xval, yval)
```

